### ISSUE TITLE
打开.md文件也会开启一个 webview 进行脑图的展示

### ISSUE THREAD

**Issue by lewiszlw** [souche/vscode-mindmap#2]
vscode版本1.33.1 (mac)，打开.md格式和.gitignore文件也会开启一个脑图展示，.md格式文件稳定复现，.gitignore文件偶现

**Comment by wangtianlun** [comment]
@lewiszlw   首先感谢您的反馈，问题已经在最新版0.0.4修复了。如果还有什么问题，请您反馈给我们，我们会第一时间进行修复和支持
