### ISSUE TITLE
保存和导出图片的图标不见了

### ISSUE THREAD

**Issue by weifengsd** [souche/vscode-mindmap#26]
VS Code version: 1.54.2
vscode-mindmap: 0.0.5

问题：
IDEA栏保存和导出图片的图标消失。

**Comment by congvmit** [comment]
@weifengsd Have you find the way to fix it?

**Comment by weifengsd** [comment]
Restore the VS Code to a small window and maximize the window,  then the save and exportToImage icons will be shown.

**Comment by leobuzhi** [comment]
> Restore the VS Code to a small window and maximize the window, then the save and exportToImage icons will be shown.

It doesn't work for me.

**Comment by weifengsd** [comment]
Try to narrow or hide the side bar of VS Code.
