### ISSUE TITLE
English buttons

### ISSUE THREAD

**Issue by rkristelijn** [souche/vscode-mindmap#3]
Hi, I would like to discuss the approach for adding translations for e.g. English. Currently the (i think) Chinese symbols are hardcoded in the html-files. 

I'm thinking about adding a setting to either show the Chinese symbols are English text and create a PR for this.

Please let me know under what circumstances you would approve a PR for this.

--
嗨，我想讨论为例如添加翻译的方法。 英语。 目前（我认为）中文符号在html文件中是硬编码的。

我正在考虑添加一个设置来显示中文符号是英文文本并为此创建PR。

请告诉我你在什么情况下批准PR。

**Comment by xinyu198736** [comment]
we can display text by vscode setting?

**Comment by wangtianlun** [comment]
@rkristelijn  We will soon support the English version.

**Comment by rkristelijn** [comment]
> @rkristelijn We will soon support the English version.

That is awesome! Let me know if/how I can help, thanks!

**Comment by wangtianlun** [comment]
English version is currently supported @rkristelijn

**Comment by wangtianlun** [comment]
version 0.0.5 @rkristelijn

**Comment by rkristelijn** [comment]
I don't see the change, can you let me know what I am doing wrong?
![image](https://user-images.githubusercontent.com/21142148/61440329-87566580-a943-11e9-8d05-a176d3e9e7f4.png)

I have installed v0.0.5 
![image](https://user-images.githubusercontent.com/21142148/61440380-a5bc6100-a943-11e9-89f8-a800c252645f.png)

configure plugin settings shows:
![image](https://user-images.githubusercontent.com/21142148/61440430-c5538980-a943-11e9-8d16-8309805b6b64.png)

**Comment by wangtianlun** [comment]
@rkristelijn   remove the "mindmap for souche" and install "vscode-mindmap"
![image](https://user-images.githubusercontent.com/8198981/61460225-e4343900-a9a0-11e9-9cc4-500352fd2923.png)

**Comment by tamerh** [comment]
Hi, I have removed and install the vscode one and still not seeing the english. is there any other trick?thanks

**Comment by tamerh** [comment]
in fact it seems most of the page is english but popus windows not.

**Comment by rkristelijn** [comment]
![image](https://user-images.githubusercontent.com/21142148/61644754-958ae580-aca5-11e9-801e-6fb1602e4574.png)

谢谢

**Comment by martin-dufka** [comment]
and what about mouse right click?  :)


![screenshot](https://user-images.githubusercontent.com/3446877/71038332-e6521d80-2121-11ea-8295-e899829cfac6.jpg)
